// DAILY PLANNER THAT STORES IMPORTANT EVENTS FOR EFFECTIVE TIME MANAGEMENT

// BUILD CALENDAR


//CODE USING LUXON THAT DISPLAYS CURRENT DAY AND DATE TARGETING id="currentDay"

//BLOCKS -
// 1) EACH BLOCK WILL BE COLOR CODED TO REFLECT IF IT IS PAST PRESENT OR FUTURE

// 2) CAN BE SELECTED AND TEXT CAN BE ENTERED 

// 3) WHEN THE SAVE BUTTON IS PRESSED THEN THE EVENT IS SAVED INTO LOCAL STORAGE


//WHEN THE PAGE IS REFRESHED THEN THE SAVE PERSISTS IN LOCAL STORAGE

https://moment.github.io/luxon/


//variables

var DateTime = luxon.DateTime;

var now = DateTime.local();

console.log('Datetime');
